### ISSUE TITLE
Google analytics integration

### ISSUE THREAD

**Issue by jobburg** [Rolmops/Zwabber#22]

**Comment by ldebruijn** [comment]
Als we geen butje cookie pop up willen ook deze instellingen toepassen:
[Hit me](http://www.marketingfacts.nl/berichten/hoe-pas-je-google-analytics-aan-op-de-nieuwe-cookiewet)

**Comment by Rolmops** [comment]
Ik heb de instellingen aangehouden zoals die in het artikel van Lars worden beschreven
